config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  resources :users
  resources :posts
  root            'static_pages#home'
  get 'help'    =>'static_pages#help'
  get 'about'   =>'static_pages#about'
  get 'contact' =>'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'  =>  'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'search' => 'search#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  acts_as_votable
  acts_as_commentable
  
  mount_uploader :attachment, AvatarUploader
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save {email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }

    has_secure_password
    validates :password, length: { minimum: 6 }


    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                            BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_commentable, only: :create
  respond_to :js

  def create
    @comment = @commentable.comments.new do |comment|
      comment.comment = params[:comment_text]
      comment.user = current_user
    end
    @comment.save
    redirect_to root_path
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment_id = params[:id]
    @comment.destroy
  end

  private
  def find_commentable
    @commentable_type = params[:commentable_type].classify
    @commentable = @commentable_type.constantize.find(params[:commentable_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def front

  	puts "Fron------------------t"
  	@post = Post.new
  end

  def index
  	@post = Post.new
  end

  def profile

    if current_user
    	@post = Post.new
    	@current_user_posts = current_user.posts
      @username = params[:id]
    else
      redirect_to root_path, :notice => "User not found"
    end
    #if (User.find_by_username(params[:id]))
    #  @username = params[:id]
    #else
     # redirect_to root_path, :notice => "User not found"
    #end
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_likeable
  before_action :authenticate_user!
  respond_to :js

  def create
    @likeable.liked_by current_user
  end

  def destroy
    @likeable.disliked_by current_user
  end

  private
  def find_likeable
    @likeable_type = params[:likeable_type].classify
    @likeable = @likeable_type.constantize.find(params[:likeable_id])
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
  @post = Post.new(post_params) do |post|
    post.user = current_user
  end
  if @post.save
    redirect_to root_path
  else
    redirect_to root_path, notice: @post.errors.full_messages.first
  end
end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post = Post.new
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #upvote_from user
  #downvote_from user
  def upvote
    if current_user.voted_for? @post
      puts "true ======================\n\n"
      @post.unvote_up current_user
    #  @post.downvote
      #redirect_to root_path
    else
      @post.upvote_from current_user
      redirect_to posts_path
    end

  end

  def downvote
    @post.downvote_from current_user
    redirect_to posts_path

 

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:attachment, :content, :user_id)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

def search
    if params[:q].nil?
    @posts = []
  else
    @posts = Post.search params[:q]
  end

end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])

  end

  def new
    @user = User.new
  end

  def create
      @user = User.new(user_params)
      if @user.save
        log_in @user
        flash[:success] = "Welcome to share exp"
        redirect_to user_url(@user)
      else
        render 'new'
      end
  end

  private

      def user_params
          params.require(:user).permit(:name,:email, :password,
                                        :password_confirmation)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Return the full title on a per-page basis
    def full_title(page_title='')
        base_title = 'Ruby on Rails Tutorial share exp'
        if page_title.empty?
            base_title
        else
            "#{page_title} | #{base_title}"
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    #Log in the given user
    def log_in(user)
        session[:user_id] = user.id

    end

    #Return the current logged-in user(if any)
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    #Returns true if the user is logged in, false otherwise
    def logged_in?
        !current_user.nil?
    end

    #Logs out hte current user.
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    #Return Gravatar for the given user
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>">
    <%= render 'shared/avatar', :user => current_user %>
  <!--<div class="col-lg-15 col-lg-offset-0 ">-->
  <div class="paragraph">
   <div class="content">
      <div class="row">
        <span class="text"><%= comment.comment %></span>
        </div>
        <div class="pull-right">
          <% if belongs_to_user?(comment) %>
            <%= link_to comment_path(comment), method: :delete, class: '  btn btn-danger btn-sm', remote: true do %>
              delete
            <% end %>
          <% end %>
      </div>
    </div>
    <hr>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_tag comments_path(commentable_type: commentable.class.to_s, commentable_id: commentable.id), method: :post, remote: true do %>
  <div class="form-group">
    <%= text_area_tag :comment_text, nil, placeholder: 'Enter Comment', class: 'form-control' %>
  </div>
  <%= submit_tag :comment, class: 'btn btn-primary' %>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/find_commentable.html.erb
<h1>Comments#find_commentable</h1>
<p>Find me in app/views/comments/find_commentable.html.erb</p>

app/views/home/_new_post.html.erb
<%= form_for(@post) do |f| %>
  <div class="form-group">
    <%= f.label 'Update status' %><br>
      <%= f.text_area :content, class: 'form-control', autofocus: true, 
          placeholder: 'What\'s up?' %>
      <%= f.file_field :attachment %>
  </div>
  <%= f.submit :post, class: 'btn btn-primary'%>
<% end %>

app/views/home/front.html.erb
<h1>Home#front</h1>

app/views/home/index.html.erb
<h1>Home#index</h1>

<%= render 'new_post', remote: false %>

<br /><hr /><br />

<div class="jumbotron">
hello
</div>

app/views/home/profile.html.erb
<h2> <%= current_user.email %> </h2>

<%= render 'shared/avatar', :user => current_user %>
<%= render 'new_post', remote: false %>
<br /><hr /><br />

<% @current_user_posts.each do |current_user_post| %>
<div id="post-<%= current_user_post.id %>" class="post">
  <div class="row">
   


    <div class="col-lg-15">
      <div class="row">
        <%= render template: 'posts/show', :locals=>{:post => current_user_post} %>
    </div>
  </div>
  <br /><hr /><br />
      </div>
  </div>
 <% end %>
 

app/views/likes/_form.html.erb
  <% if current_user.liked? likeable %>
  <%= form_tag unlike_path(likeable_type: likeable.class.to_s, likeable_id: likeable.id), method: :post, remote: true do %>
    <% button_tag class: 'btn btn-block liked' do %>
      <%= fa_icon 'thumbs-up' %> unlike
    <% end %>
  <% end %>
<% else %>
  <%= form_tag like_path(likeable_type: likeable.class.to_s, likeable_id: likeable.id), remote: true do %>
    <% button_tag class: 'btn btn-block' do %>
      <%= fa_icon 'thumbs-up' %> like
    <% end %>
  <% end %>
<% end %>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :attachment %>
    <%= f.text_field :attachment %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<p id="notice"><%= notice %></p>
<div id="post_#{post.id}">
  <%= "post_#{post.id}" %>
<p>
  <strong>User:</strong>
  <%= post.user.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= post.content %>
</p>

<% if (post.attachment).present? %>
<p>
  <strong>Attachment:</strong>
  <div class="row">
    <div align="center">
      <a href="" class="thumbnail" style="width:95%;">
        <img src=<%=post.attachment %>>
      </a>
    </div>
  </div>
</p>
<% end %>
<div class="caption" style="text-align:center;">
  <%= link_to like_post_path(post), class: "like", method: :put, remote: true do %>
  <button type="button" class="btn btn-info" aria-label="Left Align">
    <span class="glyphicon glyphicon-thumbs-up glyphocon-align-center" aria-hidden="true"></span>
    <span class="badge"><%= post.get_upvotes.size %></span>
  </button>
  <% end %>
  <%= link_to unlike_post_path(post), class: "like", method: :put do %>
  <button type="button" class="btn btn-info" aria-label="Left Align">
    <span class="glyphicon glyphicon-thumbs-down glyphocon-align-center" aria-hidden="true"></span>
    <span class="badge"><%= post.get_downvotes.size %></span>
  </button>
  <% end %>
</div>
</div>
<hr />




<%= link_to 'Edit', edit_post_path(post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/_post.js.erb
$("#post_#{@post.id}").load(location.href+" #post_#{@post.id}>*","");

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Attachment</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.attachment %></td>
        <td><%= post.content %></td>
        <td><%= post.user %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% post ||= @post %>
<div id="post-<%= post.id %>" class="post">
  <div class="row">
   
    <div class="col-lg-15 col-lg-offset-2 well">
      <%= render 'shared/avatar', :user => post.user %>
      <div class="row">
        
      <%= render partial: 'posts/post', :locals=>{:post => post} %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-15 col-lg-offset-2 well">
    <h4>Comments</h4>
    
    <%= render 'comments/form', commentable: post %>
    <hr />
    <% @comments = post.comments %>
    <% @comments.each do |comment| %>
    <%= render 'comments/comment', commentable: post, comment: comment %>
    <% end %>
    <!-- <div class="comments">
       render(@comments) || render('shared/no_resource', resources: 'Comments') 
    </div> -->
  </div>
</div>

app/views/posts/upvote.js.erb
$("#post_#{@post.id}").load(location.href+" #post_#{@post.id}>*","");

app/views/search/search.html.erb
<h1>Posts Search</h1>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>

<ul>
  <% @posts.each do |post| %>
    <li>
      <h3>
        <%= link_to post.try(:highlight).try(:title) ? post.highlight.title[0].html_safe : post.title,
          controller: "posts",
          action: "show",
          id: post._id%>
      </h3>
      <% if post.try(:highlight).try(:content) %>
        <% post.highlight.content.each do |snippet| %>
          <p><%= snippet.html_safe %>...</p>
        <% end %>
      <% end %>

      <% if post.try(:highlight).try(:category) %>
        <% post.highlight.category.each do |snippet| %>
          <p><%= snippet.html_safe %>...</p>
        <% end %>
      <% end %>

    </li>
  <% end %>
</ul>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
    <p>
    The <a href="http://railstutorial.org"><em>ROR tutorial</em></a> is a
        <a href="http://railstutorial.org/book">book</a> and
        <a href="http://screencasts.railstutorial.org">screencast series</a>
        to teach web delvelpment with
           <a href="http://rubyonrails.org">Ruby on rails</a>
           This is the Share Experience
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact</h1>
<p>
    Contact the Ruby on Rails tutorial at the
        <a href="http://www.railstutorial.org/#conatct"> Rails Tutorial Help Section</a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>Help</h1>
<p>
    Get help on the Ruby on Rails tutorial at the
        <a href="http://www.railstutorial.org/#help"> Rails Tutorial Help Section</a>
    <p>
        To get hepl on this share exp, see the
        <a href="http://www.railstutorial.org/book">
             <em>Ruby on Rails Tutorial Book</em>
        </a>
    </p>
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
    <h1>Welcome to Share Experience!</h1>

    <h2>
        Share your experience with the World, in all fields!
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>

</div>
<!--
<%= link_to image_tag("rails.png", alt: "Rails logo"),
'http://rubyonrails.org/' %> -->

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>

            <%= render 'shared/error_messages'%>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation,"Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            <%= f.submit "Create Account", class: "btn btn-primary" %>
        <% end %>
    </div>

</div>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user%>
                <%= @user.name %>
            </h1>
        </section>
    </aside>
</div>